name: Build project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: develop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: docker/build-push-action@v1
        with:
          repository: givery/prince-shotoku
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
